server:
  port: 8098 #服务端口
spring:
  profiles:
    active: dev #环境配置
  application:
    name: service-consumer #服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8785

